<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>nim</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~N</string>
	<key>name</key>
	<string>Nim</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(^[ \t]+)?(?=##)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.whitespace.comment.leading.nim</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?!\G)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>##</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.nim</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\n</string>
					<key>name</key>
					<string>comment.line.number-sign.doc-comment.nim</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^[ \t]+)?(?=#)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.whitespace.comment.leading.nim</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?!\G)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>#</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.nim</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\n</string>
					<key>name</key>
					<string>comment.line.number-sign.nim</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>A nim procedure or method</string>
			<key>name</key>
			<string>meta.proc.nim</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\b(proc|method|template|macro|iterator|converter)\s+\`?([^\:\{\s\`\*\(]*)\`?(\s*\*)?\s*(\(|\=|:|\[|\n|\{)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.proc.nim</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.nim</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.control.export</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.nim</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>discard """</string>
			<key>comment</key>
			<string>A discarded triple string literal comment</string>
			<key>end</key>
			<string>"""(?!")</string>
			<key>name</key>
			<string>comment.line.discarded.nim</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>A float literal</string>
			<key>match</key>
			<string>\b\d[_\d]*((\.[_\d]+([eE][\+\-]?\d[_\d]*)?)|([eE][\+\-]?\d[_\d]*))('[fF](32|64))?</string>
			<key>name</key>
			<string>constant.numeric.float.decimal.nim</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>A hexadecimal literal</string>
			<key>match</key>
			<string>\b(0[xX]\h[_\h]*)('(([iIuUfF](8|16|32|64))|[uU]))?</string>
			<key>name</key>
			<string>constant.numeric.integer.hexadecimal.nim</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>A base-8 integer literal</string>
			<key>match</key>
			<string>\b(0o[0-7][_0-7]*)('(([iIuUfF](8|16|32|64))|[uU]))?</string>
			<key>name</key>
			<string>constant.numeric.integer.octal.nim</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>A base-2 integer literal</string>
			<key>match</key>
			<string>\b(0(b|B)[01][_01]*)('(([iIuUfF](8|16|32|64))|[uU]))?</string>
			<key>name</key>
			<string>constant.numeric.integer.binary.nim</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>A base-10 integer literal</string>
			<key>match</key>
			<string>\b(\d[_\d]*)('(([iIuUfF](8|16|32|64))|[uU]))?</string>
			<key>name</key>
			<string>constant.numeric.integer.decimal.nim</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Operator as function name</string>
			<key>match</key>
			<string>(?&lt;=\`)[^\` ]+(?=\`)</string>
			<key>name</key>
			<string>entity.name.function.nim</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.export</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Export qualifier.</string>
			<key>match</key>
			<string>\b\s*(\*)(?:\s*(?=[,:])|\s+(?=[=]))</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Language Constants.</string>
			<key>match</key>
			<string>\b(true|false|inf|nil)\b</string>
			<key>name</key>
			<string>constant.language.nim</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Keywords that affect program control flow or scope.</string>
			<key>match</key>
			<string>\b(block|break|case|continue|do|elif|else|end|except|finally|for|if|raise|return|try|when|while|yield)\b</string>
			<key>name</key>
			<string>keyword.control.nim</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Keyword boolean operators for expressions.</string>
			<key>match</key>
			<string>(\b(and|in|is|isnot|not|notin|or|xor)\b)</string>
			<key>name</key>
			<string>keyword.operator.boolean.nim</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Generic operators for expressions.</string>
			<key>match</key>
			<string>(=|\+|-|\*|/|&lt;|&gt;|@|\$|~|&amp;|%|!|\?|\^|\.|:|\\)+</string>
			<key>name</key>
			<string>keyword.operator.nim</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Other keywords.</string>
			<key>match</key>
			<string>(\b(addr|as|atomic|bind|cast|const|converter|defer|discard|distinct|div|enum|export|from|import|include|let|mod|mixin|object|of|ptr|ref|shl|shr|static|type|var)\b)</string>
			<key>name</key>
			<string>keyword.other.nim</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Invalid and unused keywords.</string>
			<key>match</key>
			<string>(\b(generic|interface|lambda|out|shared|with|without)\b)</string>
			<key>name</key>
			<string>invalid.illegal.invalid-keyword.nim</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Common functions</string>
			<key>match</key>
			<string>\b(new|await|assert|echo|defined|declared|newException|countup|countdown|high|low)\b</string>
			<key>name</key>
			<string>keyword.other.common.function.nim</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Built-in, concrete types.</string>
			<key>match</key>
			<string>\b(((uint|int|float)(8|16|32|64)?)|bool|string|auto|cstring|char|byte|tobject|typedesc|stmt|expr|any|untyped|typed)\b</string>
			<key>name</key>
			<string>storage.type.concrete.nim</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Built-in, generic types.</string>
			<key>match</key>
			<string>\b(range|array|seq|tuple|natural|set|ref|ptr|pointer)\b</string>
			<key>name</key>
			<string>storage.type.generic.nim</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Function types</string>
			<key>match</key>
			<string>\b(proc|iterator|method|template|macro)\b</string>
			<key>name</key>
			<string>storage.type.function.nim</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Special types.</string>
			<key>match</key>
			<string>\b(openarray|varargs|void)\b</string>
			<key>name</key>
			<string>storage.type.generic.nim</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Other constants.</string>
			<key>match</key>
			<string>\b[A-Z][A-Z0-9_]+\b</string>
			<key>name</key>
			<string>support.constant.nim</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Other types.</string>
			<key>match</key>
			<string>\b[A-Z]\w+\b</string>
			<key>name</key>
			<string>support.type.nim</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Function call.</string>
			<key>match</key>
			<string>\b\w+\b(?=\()</string>
			<key>name</key>
			<string>support.function.any-method.nim</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Dot access.</string>
			<key>match</key>
			<string>(?&lt;=\b\.)\b\w+</string>
			<key>name</key>
			<string>variable.other.dot-access.nim</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#string_quoted_triple_raw</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#string_quoted_triple</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#string_quoted_double_raw</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#string_quoted_double</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#string_quoted_single</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^\s*)?(?=\{\.emit: ?""")</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.whitespace.embedded.leading.nim</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?!\G)(\s*$\n?)?</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.whitespace.embedded.trailing.nim</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\{\.(emit:) ?(""")</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.nim</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.begin.nim</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>source.c</string>
					<key>end</key>
					<string>(")""(?!")(\.\})?</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.end.nim</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>source.c</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.embedded.block.c</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>\`</string>
							<key>end</key>
							<string>\`</string>
							<key>name</key>
							<string>keyword.operator.nim</string>
						</dict>
						<dict>
							<key>include</key>
							<string>source.c</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\{\.</string>
			<key>end</key>
			<string>\.\}</string>
			<key>name</key>
			<string>meta.preprocessor.nim</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string_quoted_triple</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string_quoted_double_raw</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string_quoted_double</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string_quoted_single</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^\s*)?(?=asm """)</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.whitespace.embedded.leading.nim</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?!\G)(\s*$\n?)?</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.whitespace.embedded.trailing.nim</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(asm) (""")</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.nim</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.begin.nim</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>source.asm</string>
					<key>end</key>
					<string>(")""(?!")</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.end.nim</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>source.asm</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.embedded.block.asm</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>\`</string>
							<key>end</key>
							<string>\`</string>
							<key>name</key>
							<string>keyword.operator.nim</string>
						</dict>
						<dict>
							<key>include</key>
							<string>source.asm</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.nim</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.nim</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>tmpl specifier</string>
			<key>match</key>
			<string>(tmpl(i)?)(?=( (html|xml|js|css|glsl|md))?""")</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^\s*)?(?=html""")</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.whitespace.embedded.leading.nim</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?!\G)(\s*$\n?)?</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.whitespace.embedded.trailing.nim</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(html)(""")</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.nim</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.begin.nim</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>text.html</string>
					<key>end</key>
					<string>(")""(?!")</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.end.nim</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>text.html</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.embedded.block.html</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>(?&lt;!\$)(\$)\(</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.nim</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.nim</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>(?&lt;!\$)(\$)\{</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.nim</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.nim</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\}</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.nim</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>(?&lt;!\$)(\$)(for|while|case|of|when|if|else|elif)( )</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.nim</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.nim</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(\{|\n)</string>
							<key>endCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>plain</string>
								</dict>
							</dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.nim</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>match</key>
							<string>(?&lt;!\$)(\$\w+)</string>
							<key>name</key>
							<string>keyword.operator.nim</string>
						</dict>
						<dict>
							<key>include</key>
							<string>text.html.basic</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^\s*)?(?=xml""")</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.whitespace.embedded.leading.nim</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?!\G)(\s*$\n?)?</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.whitespace.embedded.trailing.nim</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(xml)(""")</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.nim</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.begin.nim</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>text.xml</string>
					<key>end</key>
					<string>(")""(?!")</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.end.nim</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>text.xml</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.embedded.block.xml</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>(?&lt;!\$)(\$)\(</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.nim</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.nim</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>(?&lt;!\$)(\$)\{</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.nim</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.nim</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\}</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.nim</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>(?&lt;!\$)(\$)(for|while|case|of|when|if|else|elif)( )</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.nim</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.nim</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(\{|\n)</string>
							<key>endCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>plain</string>
								</dict>
							</dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.nim</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>match</key>
							<string>(?&lt;!\$)(\$\w+)</string>
							<key>name</key>
							<string>keyword.operator.nim</string>
						</dict>
						<dict>
							<key>include</key>
							<string>text.xml</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^\s*)?(?=js""")</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.whitespace.embedded.leading.nim</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?!\G)(\s*$\n?)?</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.whitespace.embedded.trailing.nim</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(js)(""")</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.nim</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.begin.nim</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>source.js</string>
					<key>end</key>
					<string>(")""(?!")</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.end.nim</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>source.js</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.embedded.block.js</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>(?&lt;!\$)(\$)\(</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.nim</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.nim</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>(?&lt;!\$)(\$)\{</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.nim</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.nim</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\}</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.nim</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>(?&lt;!\$)(\$)(for|while|case|of|when|if|else|elif)( )</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.nim</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.nim</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(\{|\n)</string>
							<key>endCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>plain</string>
								</dict>
							</dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.nim</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>match</key>
							<string>(?&lt;!\$)(\$\w+)</string>
							<key>name</key>
							<string>keyword.operator.nim</string>
						</dict>
						<dict>
							<key>include</key>
							<string>source.js</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^\s*)?(?=css""")</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.whitespace.embedded.leading.nim</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?!\G)(\s*$\n?)?</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.whitespace.embedded.trailing.nim</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(css)(""")</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.nim</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.begin.nim</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>source.css</string>
					<key>end</key>
					<string>(")""(?!")</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.end.nim</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>source.css</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.embedded.block.css</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>(?&lt;!\$)(\$)\(</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.nim</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.nim</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>(?&lt;!\$)(\$)\{</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.nim</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.nim</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\}</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.nim</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>(?&lt;!\$)(\$)(for|while|case|of|when|if|else|elif)( )</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.nim</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.nim</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(\{|\n)</string>
							<key>endCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>plain</string>
								</dict>
							</dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.nim</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>match</key>
							<string>(?&lt;!\$)(\$\w+)</string>
							<key>name</key>
							<string>keyword.operator.nim</string>
						</dict>
						<dict>
							<key>include</key>
							<string>source.css</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^\s*)?(?=glsl""")</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.whitespace.embedded.leading.nim</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?!\G)(\s*$\n?)?</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.whitespace.embedded.trailing.nim</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(glsl)(""")</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.nim</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.begin.nim</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>source.glsl</string>
					<key>end</key>
					<string>(")""(?!")</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.end.nim</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>source.glsl</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.embedded.block.glsl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>(?&lt;!\$)(\$)\(</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.nim</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.nim</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>(?&lt;!\$)(\$)\{</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.nim</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.nim</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\}</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.nim</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>(?&lt;!\$)(\$)(for|while|case|of|when|if|else|elif)( )</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.nim</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.nim</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(\{|\n)</string>
							<key>endCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>plain</string>
								</dict>
							</dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.nim</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>match</key>
							<string>(?&lt;!\$)(\$\w+)</string>
							<key>name</key>
							<string>keyword.operator.nim</string>
						</dict>
						<dict>
							<key>include</key>
							<string>source.glsl</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^\s*)?(?=md""")</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.whitespace.embedded.leading.nim</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?!\G)(\s*$\n?)?</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.whitespace.embedded.trailing.nim</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(md)(""")</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.nim</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.begin.nim</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>text.html.markdown</string>
					<key>end</key>
					<string>(")""(?!")</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.end.nim</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>text.html.markdown</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.embedded.block.html.markdown</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>(?&lt;!\$)(\$)\(</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.nim</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.nim</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>(?&lt;!\$)(\$)\{</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.nim</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.nim</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\}</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.nim</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>(?&lt;!\$)(\$)(for|while|case|of|when|if|else|elif)( )</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.nim</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.nim</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(\{|\n)</string>
							<key>endCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>plain</string>
								</dict>
							</dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.nim</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>match</key>
							<string>(?&lt;!\$)(\$\w+)</string>
							<key>name</key>
							<string>keyword.operator.nim</string>
						</dict>
						<dict>
							<key>include</key>
							<string>text.html.markdown</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>escaped_char</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\[nN]</string>
					<key>name</key>
					<string>constant.character.escape.newline.nim</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\[cC]|\\[rR]</string>
					<key>name</key>
					<string>constant.character.escape.carriagereturn.nim</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\[lL]</string>
					<key>name</key>
					<string>constant.character.escape.linefeed.nim</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\[fF]</string>
					<key>name</key>
					<string>constant.character.escape.formfeed.nim</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\[tT]</string>
					<key>name</key>
					<string>constant.character.escape.tabulator.nim</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\[vV]</string>
					<key>name</key>
					<string>constant.character.escape.verticaltabulator.nim</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\\"</string>
					<key>name</key>
					<string>constant.character.escape.double-quote.nim</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\'</string>
					<key>name</key>
					<string>constant.character.escape.single-quote.nim</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\[0-9]+</string>
					<key>name</key>
					<string>constant.character.escape.chardecimalvalue.nim</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\[aA]</string>
					<key>name</key>
					<string>constant.character.escape.alert.nim</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\[bB]</string>
					<key>name</key>
					<string>constant.character.escape.backspace.nim</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\[eE]</string>
					<key>name</key>
					<string>constant.character.escape.escape.nim</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\[xX]\h\h</string>
					<key>name</key>
					<string>constant.character.escape.hex.nim</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\\\</string>
					<key>name</key>
					<string>constant.character.escape.backslash.nim</string>
				</dict>
			</array>
		</dict>
		<key>string_quoted_double</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.nim</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Double Quoted String</string>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.nim</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.nim</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#escaped_char</string>
				</dict>
			</array>
		</dict>
		<key>string_quoted_double_raw</key>
		<dict>
			<key>begin</key>
			<string>r"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.nim</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Raw Double Quoted String</string>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.nim</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.raw.nim</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>""</string>
				</dict>
			</array>
		</dict>
		<key>string_quoted_single</key>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.nim</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Single quoted character literal</string>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.nim</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.nim</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\n</string>
					<key>name</key>
					<string>invalid.illegal.character.nim</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#escaped_char</string>
				</dict>
				<dict>
					<key>match</key>
					<string>([^']{2,}?)</string>
					<key>name</key>
					<string>invalid.illegal.character.nim</string>
				</dict>
			</array>
		</dict>
		<key>string_quoted_triple</key>
		<dict>
			<key>begin</key>
			<string>"""</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.nim</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Triple Quoted String</string>
			<key>end</key>
			<string>"""(?!")</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.nim</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.triple.nim</string>
		</dict>
		<key>string_quoted_triple_raw</key>
		<dict>
			<key>begin</key>
			<string>r"""</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.nim</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Raw Triple Quoted String</string>
			<key>end</key>
			<string>"""(?!")</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.nim</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.triple.raw.nim</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.nim</string>
	<key>uuid</key>
	<string>6DD62CE8-B129-4554-BD8E-CE5DB490E5A4</string>
</dict>
</plist>
